name: Build KPM
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download KernelPatch Source
        run: |
          git clone https://github.com/bmax121/KernelPatch.git

      - name: Compile and Link
        run: |
          export NDK_PATH=$ANDROID_NDK_LATEST_HOME
          export KP_DIR=$(pwd)/KernelPatch
          make ARCH=arm64

      - name: Upload KPM
        uses: actions/upload-artifact@v4
        with:
          name: Zenfone-KPM
          path: hello.kpm
